- name: Upload E2E test result to kubernetes testgrid
  environment: '{{ global_env }}'
  ignore_errors: yes  # the test run should not fail when upload doesnt work
  shell:
    executable: /bin/bash
    cmd: |
      set -ex

      # install gsutil, upload_e2e.py depends on it
      export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
      echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
      curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add
      apt-get update && sudo apt-get install google-cloud-sdk --yes
      apt-get install google-cloud-sdk-app-engine-java --yes

      # get upload_e2e.py
      wget https://raw.githubusercontent.com/kubernetes/test-infra/master/testgrid/conformance/upload_e2e.py

      # TODO(RuiChen): Add timestamp for e2e.log in order to workaround upload_e2e.py bug
      export LOG_DIR="{{ k8s_log_dir }}"
      date  +"%b %e %H:%M:%S.999: DONE" >> $LOG_DIR/e2e.log

      PIPELINE_LOGS_DIR='pr-logs'
      if [[ '{{ zuul.pipeline }}' =~ ^periodic ]]; then
          PIPELINE_LOGS_DIR='periodic-logs'
      fi

      # upload e2e log to new google storage bucket.
      python3.7 upload_e2e.py --junit=$LOG_DIR/junit*.xml --log=$LOG_DIR/e2e.log \
          --bucket=gs://{{ upload_testgrid_bucket_name }}/$PIPELINE_LOGS_DIR/ci-'{{ zuul.job }}' \
          --key-file='{{ upload_testgrid_key_file }}'
