- name: Set google account key file path for cpo
  set_fact:
    gcp_cpo_key_file: '/tmp/gcp_cpo_key.json'

- name: Save google account key file for cpo
  shell:
    cmd: |
      echo '{{ gcp_account_cpo.key_json }}' > '{{ gcp_cpo_key_file }}'
    executable: /bin/bash
  no_log: yes
