- hosts: k8s-master
  name: Upload e2e test result
  become: yes

  roles:
    - export-gcp-account
    - role: upload-testgrid
      vars:
        upload_testgrid_bucket_name: k8s-conform-provider-openstack
        upload_testgrid_key_file: "{{ gcp_cpo_key_file }}"
